// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwRrrQFN5Uc-lXwndNiYNepS-MU0tHds',
    appId: '1:424211097750:android:150c1edb86806ffab7fab7',
    messagingSenderId: '424211097750',
    projectId: 'production-b5935',
    storageBucket: 'production-b5935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgA9ogu934DDE9M6ApU-QLiXYmzLKbixk',
    appId: '1:424211097750:ios:30ce85ee25ed4832b7fab7',
    messagingSenderId: '424211097750',
    projectId: 'production-b5935',
    storageBucket: 'production-b5935.appspot.com',
    androidClientId: '424211097750-7h4vrcptvfdui8d6jokh0t2ou4fn392b.apps.googleusercontent.com',
    iosClientId: '424211097750-61vunnfejmbnvb3k1jb8s73l1b2mv6u7.apps.googleusercontent.com',
    iosBundleId: 'com.showwcase.showwcase',
  );
}
